version: '3'

networks:
  graphql-network:
    driver: bridge

services:
  graphql-server:
    image: graphql-server
    build:
      context: ./server
      target: prod
    container_name: graphql-server
    working_dir: /server
    volumes:
      - ../server:/server
      - ../.env:/server/.env
    ports:
      - 8080:8080
    tty: true
    networks:
      - graphql-network

  graphql-db:
    image: graphql-db
    build:
      context: ./postgres
    container_name: graphql-db
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - graphql-network
