name: Testing graphql_server

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: '1.14.0'

      - name: Install dependencies
          run: |
            go version
            go get -u golang.org/x/lint/golint

      - name: Run lint
          run: |
            golint -c server/.golangci.yml
